"""File storage abstraction (section 29).

`storage_key` is the only thing persisted in the database or handed to
the frontend; it is always a path built from internal, server-generated
IDs (uuid4 hex), never from a user-supplied filename. The original
filename is kept purely as metadata for display and for the
Content-Disposition header on download.

`StorageProvider` is an abstract base so `LocalStorageProvider` (the
only implementation needed for a local, single-machine tool) can later
be swapped for an S3/Azure-backed one without touching callers.
"""

from __future__ import annotations

import hashlib
import shutil
from abc import ABC, abstractmethod
from pathlib import Path
from typing import BinaryIO, Optional

from .exceptions import PathSecurityError, ResourceLimitError

UPLOADS = "uploads"
OUTPUTS = "outputs"
THUMBNAILS = "thumbnails"
TMP = "tmp"

_CHUNK_SIZE = 1024 * 1024  # Stream in 1 MiB chunks; never load a whole PDF into RAM.


class StorageProvider(ABC):
    @abstractmethod
    def save_stream(
        self,
        category: str,
        entity_id: str,
        filename: str,
        stream: BinaryIO,
        max_size_bytes: Optional[int] = None,
    ) -> tuple[str, int, str]:
        """Persist `stream` under an internal path. Returns
        (storage_key, size_bytes, sha256_hex). Raises ResourceLimitError
        if the stream exceeds `max_size_bytes`, cleaning up the partial
        file rather than leaving it behind."""

    @abstractmethod
    def write_bytes(self, category: str, entity_id: str, filename: str, data: bytes) -> str:
        """Persist `data` (already in memory - only for small generated
        files such as thumbnails) and return its storage_key."""

    @abstractmethod
    def open_read(self, storage_key: str) -> BinaryIO: ...

    @abstractmethod
    def abs_path(self, storage_key: str) -> Path: ...

    @abstractmethod
    def exists(self, storage_key: str) -> bool: ...

    @abstractmethod
    def size(self, storage_key: str) -> int: ...

    @abstractmethod
    def delete_entity(self, category: str, entity_id: str) -> None:
        """Remove every file stored for a given (category, entity_id)."""

    @abstractmethod
    def scratch_dir(self, entity_id: str) -> Path:
        """A private temporary working directory for one job, cleaned up
        by the caller (or by retention cleanup) when done."""

    @abstractmethod
    def reserve_path(self, category: str, entity_id: str, filename: str) -> tuple[str, "Path"]:
        """For engines (PyMuPDF's `.save()`) that write a file to a path
        themselves rather than handing back bytes. Returns
        (storage_key, absolute_path); the caller is responsible for
        actually creating the file at that path."""


class LocalStorageProvider(StorageProvider):
    def __init__(self, root: Path):
        self.root = root.resolve()
        for category in (UPLOADS, OUTPUTS, THUMBNAILS, TMP):
            (self.root / category).mkdir(parents=True, exist_ok=True)

    def _safe_dir(self, category: str, entity_id: str) -> Path:
        # `entity_id` is always a uuid4 hex generated by this application,
        # never user input, but we still verify the result can't escape
        # the storage root (section 32) as defense in depth.
        candidate = (self.root / category / entity_id).resolve()
        if not candidate.is_relative_to(self.root):
            raise PathSecurityError(f"Refusing to write outside storage root: {candidate}")
        candidate.mkdir(parents=True, exist_ok=True)
        return candidate

    def save_stream(
        self,
        category: str,
        entity_id: str,
        filename: str,
        stream: BinaryIO,
        max_size_bytes: Optional[int] = None,
    ) -> tuple[str, int, str]:
        directory = self._safe_dir(category, entity_id)
        target = directory / filename
        digest = hashlib.sha256()
        written = 0
        try:
            with open(target, "wb") as out:
                while True:
                    chunk = stream.read(_CHUNK_SIZE)
                    if not chunk:
                        break
                    written += len(chunk)
                    if max_size_bytes is not None and written > max_size_bytes:
                        raise ResourceLimitError(
                            f"Upload exceeds the configured limit of {max_size_bytes} bytes."
                        )
                    digest.update(chunk)
                    out.write(chunk)
        except ResourceLimitError:
            target.unlink(missing_ok=True)
            raise
        except Exception:
            target.unlink(missing_ok=True)
            raise

        storage_key = f"{category}/{entity_id}/{filename}"
        return storage_key, written, digest.hexdigest()

    def write_bytes(self, category: str, entity_id: str, filename: str, data: bytes) -> str:
        directory = self._safe_dir(category, entity_id)
        target = (directory / filename).resolve()
        if not target.is_relative_to(directory.resolve()):
            raise PathSecurityError(f"Refusing to write outside its entity directory: {filename}")
        # `filename` can be a relative path with subdirectories (e.g.
        # "assets/image-001.png" for extracted PDF images) - the entity
        # directory itself is created by _safe_dir, but nested
        # subdirectories under it are not, so they must be created here.
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        return f"{category}/{entity_id}/{filename}"

    def abs_path(self, storage_key: str) -> Path:
        candidate = (self.root / storage_key).resolve()
        if not candidate.is_relative_to(self.root):
            raise PathSecurityError(f"Refusing to access path outside storage root: {storage_key}")
        return candidate

    def open_read(self, storage_key: str) -> BinaryIO:
        return open(self.abs_path(storage_key), "rb")

    def exists(self, storage_key: str) -> bool:
        try:
            return self.abs_path(storage_key).exists()
        except PathSecurityError:
            return False

    def size(self, storage_key: str) -> int:
        return self.abs_path(storage_key).stat().st_size

    def delete_entity(self, category: str, entity_id: str) -> None:
        directory = (self.root / category / entity_id).resolve()
        if not directory.is_relative_to(self.root):
            raise PathSecurityError(f"Refusing to delete outside storage root: {directory}")
        shutil.rmtree(directory, ignore_errors=True)

    def scratch_dir(self, entity_id: str) -> Path:
        return self._safe_dir(TMP, entity_id)

    def reserve_path(self, category: str, entity_id: str, filename: str) -> tuple[str, Path]:
        directory = self._safe_dir(category, entity_id)
        return f"{category}/{entity_id}/{filename}", directory / filename
